---
 
- hosts: all
  become: true
  tasks:

   - name: add php support for apache
     apt:
       name: 
         - libapache2-mod-php
         - nano
       update_cache: yes
       state: latest  
     when: ansible_distribution in ['Debian', 'Ubuntu']
 
   - name: install httpd package
     dnf:
       name: 
         - httpd
         - php 
       update_cache: yes
       state: latest
     when: ansible_distribution == "CentOS"
