---
 
- hosts: all
  become: true
  tasks:

   - name: install updates (CentOS)
     tags: always
     dnf:
       update_only: yes
       update_cache: yes
     when: ansible_distribution == "CentOS"
 
   - name: install updates (Ubuntu)
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:

   - name: add php support for apache
     tags: apache,apache2,ubuntu
     apt:
       name: 
         - libapache2-mod-php
         - nano
       state: latest  
     when: ansible_distribution in ['Debian', 'Ubuntu']
 
   - name: install httpd package
     tags: apache,centos,httpd
     dnf:
       name: 
         - httpd
         - php 
       state: latest
     when: ansible_distribution == "CentOS"

   - name: copy html file for site
     tags: apache,apache,apache2,httpd
     copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644


- hosts: db_servers
  become: true
  tasks:
 
   - name: install mariadb server package (CentOS)
     tags: mariadb,db,centos
     dnf:
       name: mariadb
       state: latest
     when: ansible_distribution == "CentOS"
 
   - name: install mariadb server
     tags: mariadb,db,ubuntu
     apt:
       name: mariadb-server
       state: latest
     when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
 
  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
